# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "kAThNjXwJMv/2nxhMJlm/fSCgo6ouROX24RI6/KAAEB1PV1titikcf1/aHuIXY8qjviCbQ5t5wi0riM25JQgKvXcp3f8y7JNlAz55GNNMYKbRgvY+D69NIPwuI7vT+5JIUrjv0OmB9Wv48wsdI1Nk+UoheKhU/EHJoPvTt4Mzro4ANS3Fu5QVGkNcHAb2YWEe/Ilezdg31AjrgxHOk5wY7ktV3/o8IObnNsVa5F17dgwPCAgPHe5qZ2Mg4sz6oMB8C4jo4T0cRK/H9AJIU7T38bGEwjyedHUqBsoVRHbFbEzLRgL/H+zyKiyMmMBS4CbyCg1fXuf5KtkTKHbK3R6pGbVf7FPPDGgLO+FbYMUKDy8rXdwFtFR9GP3pcpJENlFqJWez5W40v+5e7Zi6wgR7kH+dBDfBn+6VsMrldPupJyYNr+lSO+q5zOwAAkD6UpIGnflCD5McWMOyvuOERbg3ftX5cnrWOibGCYs3zSMV/M3z9YfbI4IEuXKKpOcgHg7M08I5FBhqduv4B1FeBKLErn/0x7B1yYtC2XkmLBzWGY6MPoUu36na93w0rn+5IAY1/1at1EuMxKHoUSZCKxAOn7MHRWEBJtsfTciY3H0kecnYvcs8D9dW24Et5uYjLVf+shU03dO12w0ea/H/ehXpZ//+C6v3kH/yyhPWghrIGI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
