travis:
  secure:
    BINSTAR_TOKEN: UTZOT0NXLsViaHMGiihNm90nsE3UmreCg9//CxWYeZipwXrJijZkXKJlvr2s8zj/UIUmg9WwuTUMZLdCp/fqaWyIUnqRJOjaN/c3cidccZ+QwiVjatZTQeLbOU4w1ljmxVXepUgklLdNAw7V+Hv/IFNuBkmgqKVXjnPqwQibtQOtLKwzAToTVjzlkuw6+WJ+RdIQo7iQ9TnJ5FdHc4IGfe7EmKJ8V0B/odAOg0dYDwxfshv6YmoLGmpg1NZfLvfnSHcLAwXtcfOlvUYbTGldYQAT7ILiLp3I3G0ylbqKyVXI+h8eL+nERaxGJzddVx1mL8z9jkxfdFKUzx6Z0VdE9HrTX7vct9Fz7BYuHg3M8IQCeuOBXt3qRB/PPpunUrcYKAPt2V923rsptEueFlJgvSpDMJvX9vGp0+Bz5KcNpOsg24is8IIlN36ro1Qy7pXk+a0WUyB1H7rZDluRqrWDv1NgsnUn1qaR8T/tMoyGQniXIL7jws7ekAeBghfg78bDuDSYiGo8pvDyI8B+uTrl+HfDcC5gZSh2SqnkMm6CGx32p2RWk7WNhb2/q6Eyp7ikobTIVjiV5jqLPULkl0ERjtisdU59q/xLumCxsuEzmX78l5nZlvW5XUe44yAXUtPrdTztmUjWMMZQ9QWefAnanRxUjAli6cLA6K5xN4q7mb4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
