travis:
  secure:
    BINSTAR_TOKEN: kAThNjXwJMv/2nxhMJlm/fSCgo6ouROX24RI6/KAAEB1PV1titikcf1/aHuIXY8qjviCbQ5t5wi0riM25JQgKvXcp3f8y7JNlAz55GNNMYKbRgvY+D69NIPwuI7vT+5JIUrjv0OmB9Wv48wsdI1Nk+UoheKhU/EHJoPvTt4Mzro4ANS3Fu5QVGkNcHAb2YWEe/Ilezdg31AjrgxHOk5wY7ktV3/o8IObnNsVa5F17dgwPCAgPHe5qZ2Mg4sz6oMB8C4jo4T0cRK/H9AJIU7T38bGEwjyedHUqBsoVRHbFbEzLRgL/H+zyKiyMmMBS4CbyCg1fXuf5KtkTKHbK3R6pGbVf7FPPDGgLO+FbYMUKDy8rXdwFtFR9GP3pcpJENlFqJWez5W40v+5e7Zi6wgR7kH+dBDfBn+6VsMrldPupJyYNr+lSO+q5zOwAAkD6UpIGnflCD5McWMOyvuOERbg3ftX5cnrWOibGCYs3zSMV/M3z9YfbI4IEuXKKpOcgHg7M08I5FBhqduv4B1FeBKLErn/0x7B1yYtC2XkmLBzWGY6MPoUu36na93w0rn+5IAY1/1at1EuMxKHoUSZCKxAOn7MHRWEBJtsfTciY3H0kecnYvcs8D9dW24Et5uYjLVf+shU03dO12w0ea/H/ehXpZ//+C6v3kH/yyhPWghrIGI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
