travis:
  secure:
    BINSTAR_TOKEN: oTsnGYGrOdhCvA28kc45NEflyvI2Dp209BI6mNYwQx2OMm9tFRN1wo3UNf8fOEZ3QNcTBNLa2b+qSLdfSd024vleHOD86Yemshrs35JwFVEB4Nsg5tyhbvmW/bbb/PROFqHMvvwoRcxh4J9Z/IYEk3zVmqayQS0gpVKizMWIsblE9iIXRSt2igjJ9Iemau/tbCsYhi4ou7giiDsmYI/gjUmQ12qY9/Kd3+ueZ3Rj39StngG6koi+aGt7tLS82kONxNxKIlhdELAlxpTPkFbAukxL7jUxccouGqRjUstGmMWP2s5qP4qxE4Nbc0zWWF9e0zNnk7iES4KNfK984gIkXPz+2J11fjninBlMgU7NydN4gwsSMxoxiTiQ6RKXUaOEo1CZbmjbhC8Wqudf5pnQ9BZTyoRwiwg7tkMVf+kuN6rq+hicVhM+QMKwL1v6TpMEHDeRuqn5rccEvTmdYpm+Xsu17C8sZOtfigrKMppGRDZCBHGr/2FcrRVtMvIvCPSbcj5GlVlZeEzb74jC6mq8oTC/EO2eDpu8TD65wmJFj90IykMXTkhuDcR30BOTsVtbO4TqoYdNuVBKyyTpCC6kD49p3ovRDZ+DuvvyAOoRe/C4O/CmjFjnGd2fWoonFeYqRWjMbrtnoGGSzvm2fHeu3dVhBAaE5baSivrho9eRxUQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
